org_exclude_list = [
    '0002',
    '0040',
    '08003',
    '08028',
    '1 Concourse Way',
    '1066 CX',
    '1066 CX Amsterdam',
    '10691',
    '10691 Stockholm',
    '1090',
    '151 36',
    '2100',
    '2300 RA',
    '2333 CC',
    '2333 CN',
    '3000',
    '3508 TB',
    '3584CH',
    '4057',
    '44139',
    '44227 Dortmund',
    '69120',
    '74164 St Julien-en-Genevois',
    '76100',
    '78457',
    '78457 Konstanz',
    '78467',
    '9600 RC Leiden',
    'AIMMS',
    'VU University',
    'The Netherlands',
    'The Netherlands.',
    'Amsterdam',
    'Vrije Universiteit Amsterdam',
    'Utrecht',
    'Spain',
    'Spain.',
    'Inc.',
    'UK.',
    'Denmark.',
    'Germany.',
    'Sweden.',
    'Barcelona',
    'Amsterdam Institute for Molecules',
    'Alderley ParkAlderley Park',
    'Amsterdam',
    'Amsterdam 1098 XH',
    'Archimedesweg 4',
    'Ardeystraße 67',
    'Aulich Lajos str. 26',
    'Barcelona',
    'Basel',
    'Bedfordshire MK44 1LQ',
    'Belgium.',
    'Beverwijk',
    'Bilthoven',
    'Box 657',
    'Brasil.',
    'Brussels',
    'Budapest',
    'Byk-Gulden-Str. 2',
    'CB10 1SD',
    'CH-8952',
    'CZ-25250',
    'Cambridge',
    'Cambridge CB10 1SD',
    'Cheshire',
    'Co. Dublin A94 X099',
    'College Road East Princeton',
    'Copenhagen',
    'D-20146',
    'D-24105 Kiel',
    'D-24118 Kiel',
    'DK-2200',
    'Denmark.',
    'Einsteinweg 55',
    'Enschede',
    'F-75205',
    'FBMM',
    'FI-20500',
    'Finland.',
    'Forskargatan 20',
    'France.',
    'Germany',
    'Germany.',
    'Germany. marcel.leist@uni-konstanz.de.',
    'Ghent University',
    'Givaudan',
    'Gutenbergstrasse 76',
    'Gödöllő',
    'H-1117',
    'Heidelberg',
    'Herestraat 49',
    'Hinxton',
    'Hungary.',
    'I-00133',
    'Inc.',
    'Inc. Gainesville',
    'Ispra',
    'Israel.',
    'Italy.',
    'Ithaca',
    'Konstanz',
    'L-4367',
    'Laarbeeklaan 103',
    'Lahore',
    'Lausanne',
    'Leeuwarden',
    'Leiden',
    'Leuven',
    'Lisbon',
    'London',
    'Ltd',
    'Ltd.',
    'Luxembourg.',
    'Lyngby',
    'Lynnwood Road',
    'Madras',
    'Meiring Naude Road',
    'NC3Rs',
    'NY',
    'Otto-Hahn-Strasse 11',
    'Oulu',
    'P.O. Box 2300',
    'PO Box 9500',
    'Pakistan',
    'Paris',
    'Plesmanlaan 121',
    'Portugal.',
    'Pretoria',
    'Rio de Janeiro',
    'Rome',
    'S-17121',
    'S1 2BJ',
    'SE-751 23',
    'Science Park 406',
    'Sharnbrook',
    'Sheffield',
    'Sheffield S2 4SU',
    'South Africa.',
    'Spain.',
    'Stockholm',
    'Sweden',
    'Sweden.',
    'Switzerland.',
    'Södertälje',
    'The Hague',
    'The Netherlands',
    'The Netherlands.',
    'U.K.',
    'UK.',
    'USA.',
    'Uppsala',
    'Utrecht',
    'Vienna',
    'Wageningen',
    'Wagistrasse 27',
    'ZI La Varenne 20-22 rue Henri et Gilberte Goudier 63200 RIOM',
    'and Konstanz Research School Chemical Biology',
    'the Netherlands',
    'the Netherlands.',
    '0001 Pretoria',
    '08003 Barcelona',
    '1081 HV',
    '1081 HV Amsterdam',
    '1098 XH Amsterdam',
    '2288 GK Rijswijk',
    '2333 ZA',
    '3430 S. Vermont Avenue',
    '39 Kessels Road',
    '393 Middle Huaxia Road',
    '73100 Lecce',
    'Albinusdreef 2',
    'Amsterdam.',
    'Anxiety',
    'Australia.',
    'Austria.',
    'Baltimore',
    'Boston',
    'California 90089',
    'China.',
    'Durham',
    'ELIXIR Hub',
    'Groningen',
    'Inc',
    'Johannesburg',
    'LLC',
    'Lange Kleiweg 40',
    'Leeds LS11 5PS',
    'MA',
    'MA.',
    'Müllerstrasse 178',
    'NC',
    'NC.',
    'Nigeria.',
    'P. Bag X313',
    'P.O. Box 7062 Kampala',
    'QLD 4108',
    'Roodeplaat',
    'Rotterdam',
    'Science Park 904',
    'Seattle',
    'Shanghai 201203',
    'Shanghai 201210',
    'South Africa',
    'Steinbeis SU-1866',
    'Svante Arrhenius väg 8',
    'TheNetherlands.',
    'United Kingdom of Great Britain and Northern Ireland',
    'United Kingdom.',
    'United States.',
    'Universitaetsstr. 10',
    'Universite de Lille 2',
    'Netherlands.',
    'via per Arnesano',
    'De Boelelaan 1087',
    'Los Angeles',
    'Toxicological Centre',
    'United States of America.',
    'Tygerberg',
    'Reno',
    'Padualaan 8',
    'P.O. Box557',
    'P.O. Box20',
    'P.O. Box 7086 Kampala',
    'P.O. Box 6329 Kampala',
    'P.Bag 3',
    'Oxford OX1 3TA',
    'Oxford OX1 3QU',
    'Otto-Hahn-Str. 6',
    'Otto-Hahn-Str. 15',
    'Otto-Hahn-Str. 11',
    'Nottingham NG7 2RD',
    'North Carolina 27711',
    'No. 19A Yuquan Road',
    'Nijenborgh 7',
    'New York',
    'México City',
    'Måløv DK-2760',
    'Montpellier',
    'Mexico.',
    'Massachusettts 02451',
    'Maryland 21205',
    'Manchester M13 9PL',
    'Liverpool',
    'Lille',
    'Leicester LE1 7RH',
    'Lagos',
    'IL',
    'Hunzestraat 133-A',
    'Hochbergerstrasse 60C',
    'Fiskehamnsgatan 1',
    'EA 2465',
    'Dortmund',
    'D-52074 Aachen',
    'Czech Republic.',
    'Chicago',
    'California 92078',
    'CH-8093 Zurich',
    'CH-4002',
    'Box 7050',
    'Beijing 100049',
    '9747AG',
    '90411 Nürnberg',
    '88379 Biberach an der Riss',
    '826 Zhang Heng Road',
    '8092 Zurich',
    '6710 BA',
    '6700 AN',
    '65926 Frankfurt am Main',
    '6525 GA Nijmegen',
    '555 Zuchongzhi Road',
    '5020 Bergen',
    '46022 València',
    '45000 Orléans',
    '3810-193 Aveiro',
    '30625 Hannover',
    '3030-789 Coimbra',
    '3015 GE',
    '3004-504 Coimbra',
    '2340 Beerse',
    '211 18 Malmö',
    '2000 Neuchâtel',
    '189 Guo Shou Jing Road',
    '12 Mansfield Road',
    '08172 Sant Cugat del Vallès'
]

org_uni_list = ['University',
                'Universitätsmedizin',
                'Institute',
                'Institutet',
                'MaxDelbrück',
                'MaxPlanck',
                'Université',
                'Universidad',
                'Universidade',
                'Universita',
                'Universite',
                'Universiteit',
                'Università',
                'École',
]

org_group_list = ['Theoretical Chemistry',
                  'Chemistry and Pharmaceutical Sciences',
                  'Systems Bioinformatics',
                  'Medicinal chemistry',
                  'BioAnalytical Chemistry',
                  'Organic Chemistry',
                  'Molecular Cell Physiology',
                  'E&H: Environmental Chemistry and Toxicology',
                  'Molecular and Computational Toxicology',
                  'Molecular Microbiology',
                  'E&H: Environmental Health and Toxicology',
                  'E&H: Environmental Bioanalytical Chemistry',
                  #'Bioinformatics',
                  'Integrative Bioinformatics',
                  'Environment and Health',
                  'Molecular Cell Biology',
                  'Science & Business Innovation',
                  'Bio Informatics (IBIVU)',
                  'Structural Biology',
                  'AIMSS Division of BioAnalytical Chemistry'
]

org_group_exclude_list = ['Aquatic Ecology and Toxicology Group',
                          'Bioinformatics and Computational Science (BioCoS)',
                          'Bioinformatics center',
                          'Department Environment and Health',
                          'Department of In Vitro Toxicology and Dermato-Cosmetology',
                          'Department of Molecular Cell Biology and Immunology',
                          'Division of Toxicology',
                          'European Bioinformatics Institute',
                          'European Bioinformatics Institute (EMBL-EBI)',
                          'In Vitro Toxicology and Biomedicine',
                          'LACDR/Toxicology',
                          'Membrane Bioinformatics Research Group',
                          'Molecular and Computational Toxicology',
                          'Structural Bioinformatics Laboratory',
                          'Swedish Toxicology Sciences Research Center (Swetox)',
                          'Swiss Institute of Bioinformatics',
                          'Unit of Toxicology Sciences',
                          'ZBH - Center for Bioinformatics',
                          'Algorithmic Bioinformatics',
                          'Applied Bioinformatics Group',
                          'BRC Translational Bioinformatics Unit',
                          'Bioinformatics and Systems Biology',
                          'Computational Structural Biology Group',
                          'Department of Bioscience and Bioinformatics',
                          'Department of Molecular Cell Physiology',
                          'Department of Systems Biology and Bioinformatics',
                          'Division of Molecular and Computational Toxicology',
                          'Institute for Molecular Cell Biology',
                          'Institute for Organic Chemistry',
                          'Interuniversity Institute of Bioinformatics in Brussels',
                          'Microbial Bioinformatics',
                          'Molecular Cell Biology and Immunology',
                          'Pattern Recognition and Bioinformatics Group',
                          'Structural Biology Brussels',
                          'Structural Biology Research Center',
                          'Structural Biology Research Centre',
                          'Theoretical Chemistry and ACMM',
                          'VIB-VUB Center for Structural Biology',
                          'School of'
]

org_group_map_dept = {'Theoretical Chemistry' : 'Chemistry and Pharmaceutical Sciences',
                       'Chemistry and Pharmaceutical Sciences' : 'Chemistry and Pharmaceutical Sciences',
                       'Systems Bioinformatics' : 'Molecular Cell Biology',
                       'Medicinal chemistry' : 'Chemistry and Pharmaceutical Sciences',
                       'BioAnalytical Chemistry' : 'Chemistry and Pharmaceutical Sciences',
                       'Organic Chemistry' : 'Chemistry and Pharmaceutical Sciences',
                       'Molecular Cell Physiology' : 'Molecular Cell Biology',
                       'E&H: Environmental Chemistry and Toxicology'  : 'Environment and Health',
                       'Molecular and Computational Toxicology' : 'Chemistry and Pharmaceutical Sciences',
                       'Molecular Microbiology' : 'Molecular Cell Biology',
                       'E&H: Environmental Health and Toxicology'  : 'Environment and Health',
                       'E&H: Environmental Bioanalytical Chemistry'  : 'Environment and Health',
                       'Integrative Bioinformatics' : 'Bio Informatics (IBIVU)',
                       'Environment and Health'  : 'Environment and Health',
                       'Molecular Cell Biology' : 'Molecular Cell Biology',
                       'Science & Business Innovation' : 'Chemistry and Pharmaceutical Sciences',
                       'Bio Informatics (IBIVU)' : 'Bio Informatics (IBIVU)',
                       'Structural Biology' : 'Molecular Cell Biology',
                       'AIMSS Division of BioAnalytical Chemistry' : 'Chemistry and Pharmaceutical Sciences',
                       'Environmental and Health'  : 'Environment and Health',
                       'Bioinformatics' : 'Bio Informatics (IBIVU)',
}

org_nouni_exclude_list = ['Center for Neurogenomics and Cognitive Research',
                          'Functional Genomics',
                          'Theoretical Life Sciences',
                          'Computer Science',
                          'Division of Medicinal Chemistry',
                          'Toxicology',
                          'Mathematics',
                          'Physical Chemistry',
                          'Organic Synthesis',
                          'School of Medicine',
                          'School of Life Science and Technology',
                          'School of Food Technology Nutrition and Bioengineering',
                          'School of Biosciences',
                          'Independent Researcher',
                          'In Vitro Toxicology and Biomedicine',
                          'Dept of Statistics and Quantitative Methods',
                          'Dept of Informatics',
                          'Department',
                          'Dipartimento',
                          'Bioinformatics',
                          'Molecular and Cellular Neurobiology'
                          ]