org_exclude_list = [
    '0002',
    '0040',
    '08003',
    '08028',
    '1 Concourse Way',
    '1066 CX',
    '1066 CX Amsterdam',
    '10691',
    '10691 Stockholm',
    '1090',
    '151 36',
    '2100',
    '2300 RA',
    '2333 CC',
    '2333 CN',
    '3000',
    '3508 TB',
    '3584CH',
    '4057',
    '44139',
    '44227 Dortmund',
    '69120',
    '74164 St Julien-en-Genevois',
    '76100',
    '78457',
    '78457 Konstanz',
    '78467',
    '9600 RC Leiden',
    'AIMMS',
    'VU University',
    'The Netherlands',
    'The Netherlands.',
    'Amsterdam',
    'Vrije Universiteit Amsterdam',
    'Utrecht',
    'Spain',
    'Spain.',
    'Inc.',
    'UK.',
    'Denmark.',
    'Germany.',
    'Sweden.',
    'Barcelona',
    'Amsterdam Institute for Molecules',
    'Alderley ParkAlderley Park',
    'Amsterdam',
    'Amsterdam 1098 XH',
    'Archimedesweg 4',
    'Ardeystraße 67',
    'Aulich Lajos str. 26',
    'Barcelona',
    'Basel',
    'Bedfordshire MK44 1LQ',
    'Belgium.',
    'Beverwijk',
    'Bilthoven',
    'Box 657',
    'Brasil.',
    'Brussels',
    'Budapest',
    'Byk-Gulden-Str. 2',
    'CB10 1SD',
    'CH-8952',
    'CZ-25250',
    'Cambridge',
    'Cambridge CB10 1SD',
    'Cheshire',
    'Co. Dublin A94 X099',
    'College Road East Princeton',
    'Copenhagen',
    'D-20146',
    'D-24105 Kiel',
    'D-24118 Kiel',
    'DK-2200',
    'Denmark.',
    'Einsteinweg 55',
    'Enschede',
    'F-75205',
    'FBMM',
    'FI-20500',
    'Finland.',
    'Forskargatan 20',
    'France.',
    'Germany',
    'Germany.',
    'Germany. marcel.leist@uni-konstanz.de.',
    'Ghent University',
    'Givaudan',
    'Gutenbergstrasse 76',
    'Gödöllő',
    'H-1117',
    'Heidelberg',
    'Herestraat 49',
    'Hinxton',
    'Hungary.',
    'I-00133',
    'Inc.',
    'Inc. Gainesville',
    'Ispra',
    'Israel.',
    'Italy.',
    'Ithaca',
    'Konstanz',
    'L-4367',
    'Laarbeeklaan 103',
    'Lahore',
    'Lausanne',
    'Leeuwarden',
    'Leiden',
    'Leuven',
    'Lisbon',
    'London',
    'Ltd',
    'Ltd.',
    'Luxembourg.',
    'Lyngby',
    'Lynnwood Road',
    'Madras',
    'Meiring Naude Road',
    'NC3Rs',
    'NY',
    'Otto-Hahn-Strasse 11',
    'Oulu',
    'P.O. Box 2300',
    'PO Box 9500',
    'Pakistan',
    'Paris',
    'Plesmanlaan 121',
    'Portugal.',
    'Pretoria',
    'Rio de Janeiro',
    'Rome',
    'S-17121',
    'S1 2BJ',
    'SE-751 23',
    'Science Park 406',
    'Sharnbrook',
    'Sheffield',
    'Sheffield S2 4SU',
    'South Africa.',
    'Spain.',
    'Stockholm',
    'Sweden',
    'Sweden.',
    'Switzerland.',
    'Södertälje',
    'The Hague',
    'The Netherlands',
    'The Netherlands.',
    'U.K.',
    'UK.',
    'USA.',
    'Uppsala',
    'Utrecht',
    'Vienna',
    'Wageningen',
    'Wagistrasse 27',
    'ZI La Varenne 20-22 rue Henri et Gilberte Goudier 63200 RIOM',
    'and Konstanz Research School Chemical Biology',
    'the Netherlands',
    'the Netherlands.',
]

org_uni_list = ['University']


